# ИМЕНА ПАРАМЕТРОВ НЕ МЕНЯТЬ!!!!!
# ТОЛЬКО ЗНАЧЕНИЯ

test:
  subTest:
    finalTest: "complete"

ienim:
  params:
    UpgradePower: 1

  commands:
    #описание базовой команды (/ienim)
    BaseDesc: "Команды института ИЕНиМ."

    #команда для повышения уровня чар (default: plus)
    Upgrade: "plus"

    #описание команды для повышения уровня чар
    UpgradeDesc: "Преодолеть максимальный уровень зачарования одной чары предмета в руке на +1"

  messages:
    #когда игрок не из ИЕНиМ'а
    NotIenim: "Чтобы использовать /ienim нужно вступить в ИЕНиМ!"

    #когда в руках ничего нет
    HandsEmpty: "Возьми зачарованный предмет в руки, чтобы повысить его зачаровние!"

    #когда нет зачарований максимального уровня
    NoMaxEnchants: "У предмета должно быть хотя бы одно зачарование максимального уровня, чтобы преодолеть его!"

    #когда уже есть чары выше макс уровня
    # %s - имя чары
    HasOverloaded: "У предмета уже есть зачарование с уровнем, который выше макимального: %s"

    #когда чары не максимального уровня
    # %s - имя чары
    NotMaxLvl: "Зачарование %s не максимального уровня!"

    #при успешном увеличении зачарования сверх максимума
    # %s - имя чары, %d - новый уровень
    UpgradeSuccess: "Успешно зачаровано на %s %d"

    #отделение доступных для повышения чар при /ienim plus
    PlusSeparator: "--------------------\n"

    #как будет отображаться зачарование в списке
    # %s - зачарование
    PlusEnch: "[%s]"

    #сообщение при /ienim plus
    PlusMessage: "Доступные зачарования (кликни):\n\n"