# ИМЕНА ПАРАМЕТРОВ НЕ МЕНЯТЬ!!!!!
# ТОЛЬКО ЗНАЧЕНИЯ
# НАЗВАНИЯ ПРЕДМЕТОВ ПИШЕМ В СООТВЕТСТВИИ С .propeties
# ДЛЯ ЭКРАНИРОВАНИЯ ПИШЕМ СТРОКУ В КАВЫЧКАХ (например, для переносов строки (\n) или двоеточий)
# CustomModelData берём из ресурспака

test:
  subTest:
    finalTest: "complete\nsus"

database:
  url: "jdbc:mysql://212.22.92.21:3306/apexrnga_39045"
  login: "apexrnga"
  password: "4o168PPYSIdyjFU"

cooldowns:
  #кулдауны
  #Time
  #форма записи: "d:h:m:s:ms"
  #где d - дни, h - часы, m - минуты, s - секунды, ms - миллисекунды
  #использовать только целые числа
  #AcceptableCount
  #допустимое количество использований в период кулдауна
  #пример: если энергетик можно использовать не больше 3 раз в 10 минут, то Time будет 0:0:10:0:0, а AcceptableCount будет равно 3

  #использование вейпа
  #штрафы за частое употребление искать в rtf.items.vape
  vape:
    Time: "0:0:1:0:0"
    AcceptableCount: 1
  #присоединение к институту
  join:
    Time: "2:0:0:0:0"
    AcceptableCount: 1
  #использование энергетиков
  #штрафы за частое употребление искать в uralenin.items.energetics
  energetics:
    Time: "0:0:10:0:0"
    AcceptableCount: 3
  #использование пива
  beer:
    Time: "0:0:10:0:0"
    AcceptableCount: 2
    #параметры эффектов, которые накладываются при излишнем употреблении
    effects:
      #тошнота
      nausea:
        #длительность
        Duration: 1800
        #сила, начиная с 0 (0 = 1, 1 = 2 и т.д.)
        Amplifier: 9
      #слабость
      weakness:
        #длительность
        Duration: 1800
        #сила, начиная с 0 (0 = 1, 1 = 2 и т.д.)
        Amplifier: 0
  #применение /urfu kit stroika
  stroika:
    Time: "2:0:0:0:0"
    AcceptableCount: 1

urfu:
  commands:
    #описание базовой команды /urfu
    BaseDesc: "База для команд поступления в один из институтов"

    #команда для поступления в один из институтов
    join:
      Name: "join"
      Desc: "Поступить в один из институтов"
    #команда для вывода института игрока
    info:
      Name: "info"
      Desc: "Узнать, об институте"
    #команда для вывода всех институтов
    list:
      Name: "list"
      Desc: "Посмотреть список всех институтов"
    #команда для получения наборов предметов
    kit:
      Name: "kit"
      Desc: "Команда для получения наборов предметов"
      #кит для стройматериалов, доступный ИСА
      stroika:
        #название
        Name: "stroika"
        #предметы, которые содержатся в наборе
        # писать в колонку начиная с "- " (так в yaml) записываются списки
        # формат записи: "id:count"
        # т.е. пишем id предмета и отделяем от него двоеточием количество этого предмета
        # id берём с вики
        # https://minecraft.fandom.com/ru/wiki/
        # писать в кавычках
        Items:
          - "dirt:37"
          - "diamond_axe:2"

  #сообщения игроку при использовании той или иной команды
  messages:
    list:
      #подсказка про то, что можно получить доп информацию, кликнув по названию института
      #выводится после списка институтов
      ClickHelp: "Подробную информацию об институте можно получить, кликнув по его названию или с помощью команды "

      #по сути, аргумент подсказки после предыдущего сообщения
      #если ничего не поняли, оставьте как есть
      InstituteNameHelp: "<название института>"

    join:
      #когда кулдаун на смену команды еще не истек
      Cooldown: "Вы можете менять институт не чаще, чем раз в 2 дня!"

      #когда игрок пытается вступить в институт, в котором он и так находится
      # %s - название института
      AlreadyInTarget: "Вы уже в %s!"

      #когда игрок сменил институт
      # %s - название института
      JoinSuccess: "Успешно сменен институт на %s!"

      #когда не удаётся вступить в институт (обычно из-за неправильного написания названия института)
      JoinError: "Произошла ошибка: проверьте правильность написания названия института (даже подсказки есть)"

    info:
      #когда игрок пишет команду, чтобы узнать, в каком институте находится
      #к сожалению, через %s интерактивную инфу не получится сделать, поэтому делим на 2 части
      # first - часть ДО института
      # last - часть ПОСЛЕ
      MeFirst: "Вы сейчас состоите в институте "
      MeLast: "!"

      #когда игрок не состоит ни в каком институте + помощь, как использовать команду
      # first - часть до подсказки-команды как вступить в институт
      # last - часть после
      MeNoneFirst: "Вы сейчас не состоите ни в каком институте, поступите в него командой "
      MeNoneLast: "!"

      #аргумент для подсказки как вступить в институт
      #если ничего не поняли, оставьте как есть
      MeNoneCommandArg: "<Название института>"

      #появляется, когда игрок хочет узнать о том, в каком институте другой игрок
      # first - до имени цели
      # mid - после имени, но до названия института
      # last - после названия института
      PlayerFirst: "Игрок "
      PlayerMid: " учится в институте "
      PlayerLast: "!"

      #разделитель при вызове информации об институте
      InstituteDelimer: "-----------------------"

    kit:
      NotFound: "Нет такого набора!"
      stroika:
        NotIsa: "Только игроки из ИСА могут получать этот набор!"
        Cooldown: "Мы не можете получать этот кит чаще чем раз в 2 дня!"

#далее идут институты
#несколько общих слов:
#color - код цвета, идущий после §
#смотрим здесь:
# https://minecraft.fandom.com/ru/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0
#вставляем БЕЗ §

info:
  color: "2"
  params:
    #сила эффекта огнестойкости
    FireResistAmplifier: 0

ineu:
  color: "3"

  params:
    TradeMultiplier: 0.8

isa:
  color: "4"

  items:
    leviathan:
      #имя
      Name: "Левиафан"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1

  messages:
    #сообщение, когда игрок пытается выбросить Левиафан
    DropMessage: "Вы не можете выбросить Левиафан!"
    #сообщение, когда игрок пытается убрать Левиафан из инвентаря в хранилище
    StoreMessage: "Вы не можете убрать Левиафан!"
    #сообщение, когда игрок пытается поместить Левиафан в рамку
    FrameMessage: "Нельзя класть Левиафан в рамку!"
    #сообщение, когда игрок пытается отдать Левиафан стойке для брони (что?)
    StandMessage: "Вы не можете убрать левиафан!"

ifksimp:
  color: "5"
  items:
    #Спортивный шлем
    sporthelmet:
      #имя
      Name: "Козырёк Абибас"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Спортивная куртка
    sportchestplate:
      #имя
      Name: "Куртка Адик даст"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Спортивный шлем
    sportleggings:
      #имя
      Name: "Спортивные штаны Бабидас"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Спортивный шлем
    sportboots:
      #имя
      Name: "Фирменные кроссовки Адибас"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1

ugi:
  color: "6"

  params:
    #метательная книга
    book:
      #урон по игрокам
      PlayerDamage: 40
      #урон по мобам
      MobDamage: 40
    #Минимальный уровень нужный для бесплатного зачарования
    #т.е. на данное число будет меняться цена зачарования, а потом восстанавливаться
    #ноль не ставить, так как всё ломается
    # :(
    MinExpLvl: 1

  items:
    #метательная книга
    book:
      #название
      Name: "Книга"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1

fti:
  color: "7"

  params:
    #уровень эффекта "сила", начиная с нуля
    StrengthAmplifier: 0

  items:
    #лук, который при попадании может бить молнией игрока
    thunderbow:
      #название
      Name: "лук, который при попадании может бить молнией игрока"
      #описание
      Desc:
        - "при попадании может бить молнией игрока"
      #CustomModelData
      ModelData: 1

rtf:
  color: "9"
  params:
    #длительность эффекта силы для ртф (в тиках)
    VapeDuration: 600

    #сила силы, начиная с нуля (0 = 1, 1 = 2, 2 = 3 и т.д.)
    VapeAmplifier: 0

    #длительность эффекта отравления для тех, кто не в ртф (в тиках)
    VapePoisonDuration: 600

    #сила отравления, начиная с нуля (см. выше)
    VapePoisonAmplifier: 1

    #длительность эффекта отравления при частом употреблении вейпа (в тиках)
    VapePenaltyDuration: 1200

    #сила отравления при частом употреблении вейпа, начиная с нуля
    VapePenaltyAmplifier: 1

    #сколько будет держаться облако пара (в тиках)
    SteamDuration: 1

    #радуис облака пара
    SteamRadius: 10

    #на какой высоте появляется облако пара (в блоках от ног того, что использовал вейп)
    SteamHeight: 1

    #длительность слепоты для тех, кто зашёл в пар и не в ртф (в тиках)
    SteamBlindnessDuration: 200

    #сила слепоты, считая от нуля (см. выше)
    SteamBlindnessAmplifier: 24

  items:
    #Вейп
    vape:
      #имя
      Name: "Вейп"
      #описание
      Desc:
        - "Одноразовый вейп радиста."
        - "Слишком частое употребление вредно для здоровья!"
      #CustomModelData
      ModelData: 1337
    #Чулки: нижняя часть
    socks:
      #имя
      Name: "Чулки радиста"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Чулки: верхняя часть
    longsocks:
      #имя
      Name: "Чулки радиста"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Кошачьи ушки
    catears:
      #имя
      Name: "Кошачьи ушки"
      #описание
      Desc:
        - "незаменимый компонент и компаньон"
        - "любого уважающего себя радиста,"
        - "наравне с чулочками и вейпом"
      #CustomModelData
      ModelData: 1

hti:
  color: "a"

  params:
    #Обычное пшеничное пиво
    beer:
      #Сколько здоровья лечит (2 здоровья = 1 сердце)
      Heal: 2
      #Сколько голода восстанавливает (2 единицы = 1 палка)
      Hunger: 4

    #Портер
    porter:
      #Сколько здоровья лечит (2 здоровья = 1 сердце)
      Heal: 3
      #Сколько голода восстанавливает (2 единицы = 1 палка)
      Hunger: 6

    #Красный Эль
    red_ale:
      #Сколько здоровья лечит (2 здоровья = 1 сердце)
      Heal: 2
      #Сколько голода восстанавливает (2 единицы = 1 палка)
      Hunger: 6
    #Золотое яблоко
    golden_apple:
      #Дополнительное время действия поглощения в тиках (20 тиков = 1 сек)
      AbsorbAdditionalDuration: 1200
      #Дополнительное время действия регенерации в тиках (см. выше)
      RegenAdditionalDuration: 1200
    golden_carrot:
      #Сколько дополнительного насыщения даёт золотая морковь (по умолчанию золотая морковь даёт 14.4 насыщения) (отделять точкой!)
      AdditionalSaturation: 1

  items:
    #Обычное пшеничное пиво
    beer:
      #название
      Name: "Обычное пшеничное пиво"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Портер
    porter:
      #название
      Name: "Портер"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 3
    #Красный Эль
    red_ale:
      #название
      Name: "Красный Эль"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 4
    #Улучшенное зелье
    better_potion:
      #название
      Name: "Улучшенное зелье"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 99

uralenin:
  color: "b"
  params:
    bomb:
      #цвет тумана бомбы-вонючки
      Color:
        R: 65
        G: 40
        B: 20

      #радиус тумана бомбы-вонючки
      Radius: 5

      #длительность тумана бомбы-вонючки
      Duration: 100

      #параметры эффекта отравления от бомбы-вонючки
      Poison:
        #Длительность (в тиках)
        Duration: 200
        #степень, считая от нуля
        Amplifier: 0

      #параметры эффекта тошноты от бомбы-вонючки
      Nausea:
        #Длительность (в тиках)
        Duration: 400
        #степень, считая от нуля
        Amplifier: 9

      #параметры эффекта слабости от бомбы-вонючки
      Weakness:
        #Длительность (в тиках)
        Duration: 200
        #степень, считая от нуля
        Amplifier: 0

    adrenaline:
      #параметры эффекта скорости от Адреналина
      Speed:
        #длительность (в тиках)
        Duration: 1200
        #степень, считая от нуля
        Amplifier: 1

      #параметры эффекта восстановления от Адреналина
      Regen:
        #длительность (в тиках)
        Duration: 200
        #степень, считая от нуля
        Amplifier: 0

    burn:
      #параметры эффекта скорости от Бёрна
      Speed:
        #длительность (в тиках)
        Duration: 1200
        #степень, считая от нуля
        Amplifier: 1

      #параметры эффекта огнестойкости от Бёрна
      Fireresist:
        #длительность (в тиках)
        Duration: 6000
        #степень, считая от нуля
        Amplifier: 0

    moster:
      #параметры эффекта скорости от Монстра
      Speed:
        #длительность (в тиках)
        Duration: 1200
        #степень, считая от нуля
        Amplifier: 1

    redbull:
      #параметры эффекта скорости от Рэдбулла
      Speed:
        #длительность (в тиках)
        Duration: 1200
        #степень, считая от нуля
        Amplifier: 1

      #параметры эффекта огнестойкости от Рэдбулла
      Fireresist:
        #длительность (в тиках)
        Duration: 6000
        #степень, считая от нуля
        Amplifier: 0

      #параметры эффекта восстановления от Рэдбулла
      Regen:
        #длительность (в тиках)
        Duration: 200
        #степень, считая от нуля
        Amplifier: 0

  items:
    #бомба-вонючка
    bomb:
      #название
      Name: "Банка с говном"
      #описание
      Desc: "..."
      #CustomModelData
      ModelData: 1

    #Адреналин
    adrenaline:
      #название
      Name: "Адреналин"
      #описание
      Desc: "..."
      #CustomModelData
      ModelData: 5

    #Бёрн
    burn:
      #название
      Name: "Бёрн"
      #описание
      Desc: "..."
      #CustomModelData
      ModelData: 6

    #Монстр
    monster:
      #название
      Name: "Монстр"
      #описание
      Desc: "..."
      #CustomModelData
      ModelData: 7

    #Рэдбулл
    redbull:
      #название
      Name: "Рэдбулл"
      #описание
      Desc: "..."
      #CustomModelData
      ModelData: 8

ienim:
  color: "c"
  params:
    UpgradePower: 1

  commands:
    #описание базовой команды (/ienim)
    BaseDesc: "Команды института ИЕНиМ."

    #команда для повышения уровня чар (default: plus)
    Upgrade: "plus"

    #описание команды для повышения уровня чар
    UpgradeDesc: "Преодолеть максимальный уровень зачарования одной чары предмета в руке на +1"

  messages:
    #когда игрок не из ИЕНиМ'а
    NotIenim: "Чтобы использовать /ienim нужно вступить в ИЕНиМ!"

    #когда в руках ничего нет
    HandsEmpty: "Возьми зачарованный предмет в руки, чтобы повысить его зачаровние!"

    #когда нет зачарований максимального уровня
    NoMaxEnchants: "У предмета должно быть хотя бы одно зачарование максимального уровня, чтобы преодолеть его!"

    #когда уже есть чары выше макс уровня
    # %s - имя чары
    HasOverloaded: "У предмета уже есть зачарование с уровнем, который выше макимального: %s"

    #когда чары не максимального уровня
    # %s - имя чары
    NotMaxLvl: "Зачарование %s не максимального уровня!"

    #при успешном увеличении зачарования сверх максимума
    # %s - имя чары, %d - новый уровень
    UpgradeSuccess: "Успешно зачаровано на %s %d"

    #отделение доступных для повышения чар при /ienim plus
    PlusSeparator: "--------------------\n"

    #как будет отображаться зачарование в списке
    # %s - зачарование
    PlusEnch: "[%s]"

    #сообщение при /ienim plus
    PlusMessage: "Доступные зачарования (кликни):\n\n"

    #сообщение при попытке выбросить перегруженный предмет
    DropMessage: "Вы не можете выбросить свой инструмент!"

    #сообщение при попытке переложить перегруженный предмет в сундук, верстак и т.д.
    StoreMessage: "Вы безуспешно пытаетесь избавиться от своего инструмента"

    #сообщение при попытке поместить перегруженный предмет в рамку
    FrameMessage: "Вы безуспешно пытаетесь избавиться от своего инструмента"

    #сообщение при попытке надеть на стойку для брони перегруженную броню
    StandMessage: "Вы безуспешно пытаетесь избавиться от своего инструмента"

inmit:
  color: "d"

  params:
    #Пиво для ИнМИТа
    beer:
      #Уровень эффекта поглощения (каждый уровень даёт +2 золотых сердечкка) начиная с нуля
      Amplifier: 1
      #На сколько даёт в тиках (20 тиков = 1 сек)
      Duration: 2400
      #Параметры отравления, если пьёт игрок не из ИНМиТ'а
      Poison:
        #Сила отравления начиная с нуля
        Amplifier: 1
        #Длительность в тиках (20 тиков = 1 сек)
        Duration: 200


  items:
    #Пиво для ИнМИТа
    beer:
      #название
      Name: "Пиво для ИнМИТа"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 2

#абитуриент
abit:
  color: "8"
