# ИМЕНА ПАРАМЕТРОВ НЕ МЕНЯТЬ!!!!!
# ТОЛЬКО ЗНАЧЕНИЯ
# НАЗВАНИЯ ПРЕДМЕТОВ ПИШЕМ В СООТВЕТСТВИИ С .propeties
# ДЛЯ ЭКРАНИРОВАНИЯ ПИШЕМ СТРОКУ В КАВЫЧКАХ (например, для переносов строки (\n) или двоеточий)

test:
  subTest:
    finalTest: "complete\nsus"

ienim:
  params:
    UpgradePower: 1

  commands:
    #описание базовой команды (/ienim)
    BaseDesc: "Команды института ИЕНиМ."

    #команда для повышения уровня чар (default: plus)
    Upgrade: "plus"

    #описание команды для повышения уровня чар
    UpgradeDesc: "Преодолеть максимальный уровень зачарования одной чары предмета в руке на +1"

  messages:
    #когда игрок не из ИЕНиМ'а
    NotIenim: "Чтобы использовать /ienim нужно вступить в ИЕНиМ!"

    #когда в руках ничего нет
    HandsEmpty: "Возьми зачарованный предмет в руки, чтобы повысить его зачаровние!"

    #когда нет зачарований максимального уровня
    NoMaxEnchants: "У предмета должно быть хотя бы одно зачарование максимального уровня, чтобы преодолеть его!"

    #когда уже есть чары выше макс уровня
    # %s - имя чары
    HasOverloaded: "У предмета уже есть зачарование с уровнем, который выше макимального: %s"

    #когда чары не максимального уровня
    # %s - имя чары
    NotMaxLvl: "Зачарование %s не максимального уровня!"

    #при успешном увеличении зачарования сверх максимума
    # %s - имя чары, %d - новый уровень
    UpgradeSuccess: "Успешно зачаровано на %s %d"

    #отделение доступных для повышения чар при /ienim plus
    PlusSeparator: "--------------------\n"

    #как будет отображаться зачарование в списке
    # %s - зачарование
    PlusEnch: "[%s]"

    #сообщение при /ienim plus
    PlusMessage: "Доступные зачарования (кликни):\n\n"

    #сообщение при попытке выбросить перегруженный предмет
    DropMessage: "Вы не можете выбросить свой инструмент!"

    #сообщение при попытке переложить перегруженный предмет в сундук, верстак и т.д.
    StoreMessage: "Вы безуспешно пытаетесь избавиться от своего инструмента"

    #сообщение при попытке поместить перегруженный предмет в рамку
    FrameMessage: "Вы безуспешно пытаетесь избавиться от своего инструмента"

    #сообщение при попытке надеть на стойку для брони перегруженную броню
    StandMessage: "Вы безуспешно пытаетесь избавиться от своего инструмента"

rtf:
  items:
    #Вейп
    vape:
      #имя
      Name: "Вейп"
      #описание
      Desc:
        - "Одноразовый вейп радиста."
        - "Слишком частое употребление вредно для здоровья!"
      #CustomModelData
      ModelData: 1337
    #Чулки: нижняя часть
    socks:
      #имя
      Name: "Чулки радиста"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Чулки: верхняя часть
    longsocks:
      #имя
      Name: "Чулки радиста"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Кошачьи ушки
    catears:
      #имя
      Name: "Кошачьи ушки"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1

ifksimp:
  items:
    #Спортивный шлем
    sporthelmet:
      #имя
      Name: "Козырёк Абибас"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Спортивная куртка
    sportchestplate:
      #имя
      Name: "Куртка Адик даст"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Спортивный шлем
    sportleggings:
      #имя
      Name: "Спортивные штаны Бабидас"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1
    #Спортивный шлем
    sportboots:
      #имя
      Name: "Фирменные кроссовки Адибас"
      #описание
      Desc:
        - "..."
      #CustomModelData
      ModelData: 1

