name: Umcp
version: '${project.version}'
main: org.umc.umcp.Main
api-version: 1.14
authors: [ NikitaSamkov ]
description: nu i vyser
commands:
  test:
    usage: /<command>
  urfu:
    usage: §cпопробуйте /<command> help§f
  ienim:
    usage: §cпопробуйте /<command> help§f (Могут использовать только учащиеся ИЕНиМ'а!)

depend: [Vault, LuckPerms]